### ISSUE TITLE
Ch03 Reader.java. Can't assign readerRepository.findOne(username) to UserDetails

### ISSUE THREAD

**Issue by aasril** [habuma/sbia-samples#3]
It gives this error 
`Inferred type 'S' for type parameter 'S' is not within its bound; should extend 'readinglist.Reader'`.

Intellij tells me that method `findOne` expecting type of `Example<? extends Reader>`. I checked and then also copied sample codes just in case I did **ReaderRepository.java** and **Reader.java** wrong.

**Comment by markiantorno** [comment]
I'm also having this issue...

**Comment by wdpm** [comment]
https://stackoverflow.com/questions/54050430/how-should-i-use-jparepository-findone-with-springboot
```
        auth.userDetailsService(username -> readerRepository.findById(username)
                .orElseThrow(() -> new UsernameNotFoundException("user with username " + username + " not found")));
```
